feat: UM-52 util | deep merge
Dhitpl/uchwyt-magnetyczny.pl pull request #29
Opened 2024-10-04 23:46 UTC by ingrqm

[UM-52 util | deep merge](https://github.com/users/Dhitpl/projects/1?pane=issue&itemId=82258320)

## What was the task?
Create util for deep merging two objects

## What has been changed?
- installed `react-hook-form` (we planned use it on the future for handling forms, and this library export DeepPartial type),
- created deep merge util,
- created test

## Checklist
- [x] The code has been cleaned up (unused imports, `console.log`s, etc.).
- [x] The PR has its assignee(s) selected.
- [x] The PR has its reviewer(s) selected.
- [x] The PR’s title is compliant with our `commit-lint` configuration.

2024-10-05 09:36 UTC, Juleww requested changes
Please consider my comment

2024-10-05 09:36 UTC, Juleww commented on src/utils/deep-merge/deep-merge.ts
> +    if (key in partial) {
The `key in partial` check is redundant here because you are already iterating over the keys of `partial` using `Object.keys(partial)`.

2024-10-05 11:04 UTC, ingrqm commented on src/utils/deep-merge/deep-merge.ts
> +    if (key in partial) {
Good catch!

2024-10-05 11:41 UTC, Juleww approved these changes
👌

2024-10-06 09:49 UTC, VViniarr approved these changes

2024-10-06 12:23 UTC, merged